### ISSUE TITLE
Add "on pace" stats for player season response. 

### ISSUE THREAD

**Issue by notchristophermeisner** [conrmahr/nhl-discord-bot#23]
**Is your feature request related to a problem? Please describe.**
I lose my shit absolutely, when i can't see what players are on pace for points wise. 

**Describe the ideal solution**
When Calling a player with $p -s Toews, it would be great if it told me what he's on pace for in an 82 game season, points, goals and assists wise.  (points/games *82) as the general forumla.

**Describe alternatives you've considered**
Apathy

**Additional context**
I think it could just be a single embed, "on pace" with (50-25-75) as the value, or whatever it is.

**Comment by conrmahr** [comment]
@notchristophermeisner can you answer these questions so we can cover all situations:
1. As you know, there's seasons with different total game amounts in a season: `18, 22, 24, 30, 36, 44, 48, 50, 60, 70, 74, 76, 78, 80, 82, 84`. Is `82` always the multiplier? How would you handle `$p 1986 gretzky`?
2. Would this include team stats? `W-L-OT-P`
3. How do you handle values with remainders? `50.4G-22.33333A-75.9P`
4. What would the stat embed field(s) look like?
**On Pace <#Games>**
50G-25A-75P

**Comment by notchristophermeisner** [comment]
1) I would only show it for the current year, since thats the only time on pace matters, so 82.
2) would be cool, sure.
3) round to nearest integer
4) I think that is a good way, yes. 

5) thanks buddy. looking good.
