### ISSUE TITLE
Add Cap information

### ISSUE THREAD

**Issue by notchristophermeisner** [conrmahr/nhl-discord-bot#40]
**Is your feature request related to a problem? Please describe.**

**Describe the ideal solution**
I would like a command ($c <player name>) that shows me their current contract situation.  This should include
Team
Player Name
Signing Date
yearly breakdown of contract so it can show NMC/NTC etc per year.
Pending contract status (RFA/UFA/ group 6 ufa/10.2c RFA)

**Describe alternatives you've considered**posting cap friendly links, which is cumbersome. 

**Additional context**

**Comment by conrmahr** [comment]
@notchristophermeisner, can you clarify on a couple of things?
1. Which data points are desired of the yearly breakdown? `SEASON | CLAUSE | CAP HIT | AAV | P. BONUSES | S. BONUSES | BASE SALARY | TOTAL SALARY | MINORS SALARY`
1. Where is "pending contract status" is that `Expiry Status`?
1. What about for team's pages, which data points are desired? 
`Projected Cap Hit | Projected LTIR Used | Projected Cap Space | Current Cap Space | Deadline Cap Space | Todays Cap Hit`

**Comment by notchristophermeisner** [comment]
1) season, clause,  aav
2) yes expiry status.
3) current cap space, deadline would be nice, projected ltir would be nice.
