### ISSUE TITLE
Add PIM to -o flag

### ISSUE THREAD

**Issue by notchristophermeisner** [conrmahr/nhl-discord-bot#42]
**Is your feature request related to a problem? Please describe.**
no

**Describe the ideal solution**
adding PIM to the $p -o flag, to align with the stats that show when you do use $p -y

**Describe alternatives you've considered**
not asking, but being sarcastic about it. 

**Additional context**
Thanks.

**Comment by conrmahr** [comment]
@notchristophermeisner PIM shows when you add the `-advanced flag`. For example:`$player barzal -onpace -advanced`. The embed only can do fields per line if you want to add it to the non-advanced view. You'd have to replace `+/-` or something.
